AZURE_LOCATION: 'westus3'
RESOURCE_NAME_PREFIX: 'apimdemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'apim-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'https://github.com/bradcstevens'
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'